[aziot_keys]
homedir_path = "/var/lib/aziot/keyd"
pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
pkcs11_lib_path = "/usr/lib/libmypkcs11.so"

[preloaded_keys]
est-id = "pkcs11:slot-id=0;object=est-id?pin-value=1234"
