[package]
name = "http-common"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
base64 = "0.12"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.13", optional = true }
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "0.2", features = ["dns", "tcp", "uds"], optional = true }
url = { version = "2", features = ["serde"] }

[dev-dependencies]
serde_json = "1"

[features]
default = ["tokio02"]
tokio02 = ["hyper", "tokio"]
