[provisioning]
source = "manual"
iothub_hostname = "example.azure-devices.net"
device_id = "my-device"

[provisioning.authentication]
method = "x509"

[provisioning.authentication.identity_cert]
method = "est"
common_name = "my-device"
expiry_days = 365
username = "user"
password = "password"
identity_cert = "file:///var/secrets/est-id.pem"
identity_pk = "pkcs11:slot-id=0;object=est-id?pin-value=1234"
