[package]
name = "aziot-tpmd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
backtrace = "0.3"
base64 = "0.12"
futures-util = "0.3"
http = "0.2"
hyper = "0.13"
lazy_static = "1"
percent-encoding = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "0.2", features = ["macros"] }
toml = "0.5"
url = "2"

aziot-tpm-common-http = { path = "../aziot-tpm-common-http" }
aziot-tpm = { path = "../aziot-tpm-rs" }
http-common = { path = "../../http-common" }
