[package]
name = "aziot-identityd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
description = """
The code used for Identity Service.
"""
edition = "2018"

[dependencies]
base64 = "0.12"
chrono = "0.4"
clap = "2.31"
env_logger = "0.5"
futures-util = "0.3"
http = "0.2"
hyper = "0.13"
hyper-openssl = "0.8"
lazy_static = "1"
log = "0.4"
openssl = "0.10"
percent-encoding = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "time"] }
toml = "0.5"
url = { version = "2.0", features = ["serde"] }


aziot-cert-common-http = { path = "../../cert/aziot-cert-common-http" }
aziot-cert-client-async = { path = "../../cert/aziot-cert-client-async" }
aziot-dps-client-async = { path = "../aziot-dps-client-async" }
aziot-hub-client-async = { path = "../aziot-hub-client-async" }
aziot-identity-common = { path = "../aziot-identity-common" }
aziot-identity-common-http = { path = "../aziot-identity-common-http" }
aziot-key-client = { path = "../../key/aziot-key-client" }
aziot-key-client-async = { path = "../../key/aziot-key-client-async" }
aziot-key-common = { path = "../../key/aziot-key-common" }
aziot-key-openssl-engine = { path = "../../key/aziot-key-openssl-engine" }
http-common = { path = "../../http-common" }
openssl2 = { path = "../../openssl2" }

[dev-dependencies]
test-case = "1.0.0"
