[package]
name = "aziot-identityd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
description = """
The code used for Identity Service.
"""
edition = "2018"

[dependencies]
clap = "2.31"
env_logger = "0.5"
hyper = "0.12"
log = "0.4"
tokio = { version = "0.2", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
url = "2"

aziot-common = { path = "../../common/aziot-common" }

[dev-dependencies]
test-case = "1.0.0"
