###############################################################################
# Identity Service configuration
###############################################################################
hostname = "iotedge"
homedir = "/var/lib/aziot/identityd"

[connect]
api_uri = "unix:///var/run/aziot/identityd.sock"

[listen]
api_uri = "unix:///var/run/aziot/identityd.sock"

# Identity service configuration used to associate provisioned device and module identities to host-level processes.
# This configuration will also be used to generate new module identities, if not created in Azure IoT Hub already.
[[principal]]
name = "hostdaemon1"
uid = 1001

[[principal]]
name = "hostprocess1"
idtype = "device"
uid = 1002

[[principal]]
name = "hostprocess2"
idtype = "module"
uid = 1003


[provisioning]
source = "manual"
iothub_hostname = "hubname"
device_id = "deviceid"

[provisioning.authentication]
method = "sas"
device_id_pk = "device-id"
dynamic_reprovisioning = false

# [provisioning.authentication]
# method = "x509"
# iothub_hostname = "hubname"
# device_id = "deviceid"
# device_id_cert = "device-id"
# device_id_pk = "device-id"
# dynamic_reprovisioning = false

# [provisioning]
# "source" = "dps"
# "global_endpoint" = "http://globaldevices.net"
# "scope_id" = "<ADD DPS SCOPE ID HERE>"

# [provisioning.attestation]
# "method" = "symmetric_key"
# "registration_id" = "<ADD REGISTRATION ID HERE>"
# "symmetric_key" = "device-id" #Pre-loaded Key service handle
#
# [provisioning.attestation]
# "method" = "x509"
# "identity_cert" = "device-id"
# "identity_pk" = "device-id"


# EST provisioning case
# [provisioning]
# "source" = "dps"
# "scope_id" = "<ADD dps SCOPE ID HERE>"

# [provisioning.attestation]
# "method" = "x509"
# "identity_cert" = "est"
# "identity_pk" = "est"

[endpoints]
aziot_certd = "unix:///var/run/aziot/certd.sock"
aziot_identityd = "http://localhost:8901"
aziot_keyd = "unix:///var/run/aziot/keyd.sock"
