[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "0ab1234C5D6"

[provisioning.attestation]
method = "tpm"
registration_id = "my-symmkey-devices"
