[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "0ab1234C5D6"

[provisioning.attestation]
method = "x509"
registration_id = "my-symmkey-devices"
identity_cert = "file:///var/secrets/device-id.pem"
identity_pk = "pkcs11:slot-id=0;object=device-id?pin-value=1234"

[aziot_keys]
pkcs11_lib_path = "/usr/lib/libmypkcs11.so"
pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
