[package]
name = "aziot-keyd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2021"


[dependencies]
async-trait = "0.1"
base64 = "0.13"
futures-util = "0.3"
http = "0.2"
hyper = "0.14"
lazy_static = "1"
libc = "0.2"
log = "0.4"
openssl = "0.10"
openssl-sys = "0.9"
percent-encoding = "2"
regex = "1"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["time"] }
url = "2"
wildmatch = "2"

aziot-key-common = { path = "../aziot-key-common" }
aziot-key-common-http = { path = "../aziot-key-common-http" }
aziot-keyd-config = { path = "../aziot-keyd-config" }
config-common = { path = "../../config-common", features = ["watcher"] }
http-common = { path = "../../http-common" }
