[package]
name = "aziot-key-openssl-engine"
version = "0.1.0"
license = "MIT"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"
build = "build/main.rs"


[dependencies]
base64 = "0.12"
foreign-types-shared = "0.1"
openssl = "0.10"
openssl-errors = "0.1"
openssl-sys = "0.9"

aziot-key-client = { path = "../aziot-key-client" }
aziot-key-common = { path = "../aziot-key-common" }
openssl2 = { path = "../../openssl2" }
openssl-sys2 = { path = "../../openssl-sys2" }


[build-dependencies]
openssl-build = { path = "../../openssl-build" }
