hostname = "my-device"
homedir = "/var/lib/aziot/identityd"

[provisioning]
source = "manual"
iothub_hostname = "example.azure-devices.net"
device_id = "my-device"

[provisioning.authentication]
method = "x509"
identity_cert = "device-id"
identity_pk = "device-id"

[provisioning.authentication.csr_subject]
cn = "my-device"
L = "AQ"
ST = "Antarctica"
