[package]
name = "aziot-certd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"
build = "build/main.rs"


[dependencies]
async-trait = "0.1"
base64 = "0.12"
foreign-types-shared = "0.1"
futures-util = "0.3"
hex = "0.4"
http = "0.2"
hyper = "0.13"
hyper-openssl = "0.8"
lazy_static = "1"
libc = "0.2"
log = "0.4"
openssl = "0.10"
openssl-sys = "0.9"
percent-encoding = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "0.2"
url = { version = "2", features = ["serde"] }

aziot-cert-common-http = { path = "../aziot-cert-common-http" }
aziot-key-client = { path = "../../key/aziot-key-client" }
aziot-key-common = { path = "../../key/aziot-key-common" }
aziot-key-common-http = { path = "../../key/aziot-key-common-http" }
aziot-key-openssl-engine = { path = "../../key/aziot-key-openssl-engine" }
http-common = { path = "../../http-common" }
openssl2 = { path = "../../openssl2" }


[build-dependencies]
openssl-build = { path = "../../openssl-build/" }


[dev-dependencies]
toml = "0.5"
