[aziot_keys]
homedir_path = "/var/lib/aziot/keyd"

[preloaded_keys]
device-id = "file:///var/secrets/device-id.key.pem"

[[principal]]
uid = 5556
keys = ["aziot_identityd_master_id", "aziot-dps-identity-cert-key", "device-id"]

[[principal]]
uid = 5555
keys = ["aziot-dps-identity-cert-key"]
