[aziot_keys]
homedir_path = "/var/lib/aziot/keyd"
pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
pkcs11_lib_path = "/usr/lib/libmypkcs11.so"

[preloaded_keys]
local-ca = "pkcs11:slot-id=0;object=local%2Dca?pin-value=1234"

[[principal]]
uid = 1001
keys = ["aziot_identityd_master_id", "device-id"]

[[principal]]
uid = 1000
keys = ["local-ca"]
