[package]
name = "mock-iot-server"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2021"

[dependencies]
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "server"] }
lazy_static = "1.4"
openssl = "0.10"
percent-encoding = "2"
regex = "1"
serde = "1"
serde_json = "1"
structopt = "0.3"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tokio-openssl = "0.6"
uuid = { version = "1", features = ["v4"] }

aziot-cloud-client-async = { path = "../aziot-cloud-client-async" }
aziot-identity-common = { path = "../aziot-identity-common" }
test-common = { path = "../../test-common" }
