name: 'pkcs11'

on:
- 'pull_request'
- 'push'

jobs:
  build:
    runs-on: 'ubuntu-18.04'

    strategy:
      fail-fast: false

      matrix:
        container_os:
        - 'centos:7'
        - 'debian:9-slim'
        - 'debian:10-slim'
        openssl_version:
        - '1.0'
        - '1.1.0'
        - '1.1.1'
        exclude:
        - container_os: 'centos:7'
          openssl_version: '1.1.0'
        - container_os: 'centos:7'
          openssl_version: '1.1.1'
        - container_os: 'debian:9-slim'
          openssl_version: '1.1.1'
        - container_os: 'debian:10-slim'
          openssl_version: '1.0'
        - container_os: 'debian:10-slim'
          openssl_version: '1.1.0'

    steps:
    - uses: 'actions/checkout@v1'
    - name: 'Run'
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/src" \
          -e "CONTAINER_OS=$CONTAINER_OS" \
          -e "OPENSSL_VERSION=$OPENSSL_VERSION" \
          "${{ matrix.container_os }}" \
          '/src/ci/pkcs11/build.sh'
      env:
        CONTAINER_OS: "${{ matrix.container_os }}"
        OPENSSL_VERSION: "${{ matrix.openssl_version }}"
    - name: 'Generate artifact name'
      id: 'generate-artifact-name'
      run: |
        container_os="${{ matrix.container_os }}"
        container_os="$(sed -e 's@[:/]@-@g' <<< "$container_os")"
        echo "::set-output name=artifact-name::pkcs11-test_${container_os}_openssl${{ matrix.openssl_version }}"
    - name: 'Upload'
      uses: 'actions/upload-artifact@v1'
      with:
        name: "${{ steps.generate-artifact-name.outputs.artifact-name }}"
        path: 'target/debug/pkcs11-test'


  test-softhsm:
    runs-on: 'ubuntu-18.04'

    strategy:
      fail-fast: false

      matrix:
        container_os:
        - 'centos:7'
        - 'debian:9-slim'
        - 'debian:10-slim'
        openssl_version:
        - '1.0'
        - '1.1.0'
        - '1.1.1'
        key_type:
        - 'ec-p256'
        - 'ec-p384'
        - 'ec-p521'
        - 'rsa-2048'
        - 'rsa-4096'
        exclude:
        - container_os: 'centos:7'
          openssl_version: '1.1.0'
        - container_os: 'centos:7'
          openssl_version: '1.1.1'
        - container_os: 'centos:7'
          key_type: 'ec-p521' # softhsm 2.2 and earlier do not support P-521; CentOS 7 has 2.1
        - container_os: 'debian:9-slim'
          openssl_version: '1.1.1'
        - container_os: 'debian:10-slim'
          openssl_version: '1.0'
        - container_os: 'debian:10-slim'
          openssl_version: '1.1.0'

    needs: 'build'

    steps:
    - uses: 'actions/checkout@v1'
    - name: 'Generate artifact name'
      id: 'generate-artifact-name'
      run: |
        container_os="${{ matrix.container_os }}"
        container_os="$(sed -e 's@[:/]@-@g' <<< "$container_os")"
        echo "::set-output name=artifact-name::pkcs11-test_${container_os}_openssl${{ matrix.openssl_version }}"
    - name: 'Download'
      uses: 'actions/download-artifact@v1'
      with:
        name: "${{ steps.generate-artifact-name.outputs.artifact-name }}"
        path: 'target/debug'
    - name: 'Run'
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/src" \
          -e "CONTAINER_OS=$CONTAINER_OS" \
          -e "KEY_TYPE=$KEY_TYPE" \
          -e "OPENSSL_VERSION=$OPENSSL_VERSION" \
          "${{ matrix.container_os }}" \
          '/src/ci/pkcs11/test-softhsm.sh'
      env:
        CONTAINER_OS: "${{ matrix.container_os }}"
        KEY_TYPE: "${{ matrix.key_type }}"
        OPENSSL_VERSION: "${{ matrix.openssl_version }}"
