[package]
name = "esys-sys"
version = "0.1.0"
edition = "2021"
links = "tss2-esys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcti-sys = { path = "../tcti-sys" }
types-sys = { path = "../types-sys" }

[build-dependencies]
bindgen = { version = "0.69", features = ["runtime"], default-features = false }
# NOTE: Version >= 0.3.20 necessary for cross-builds.
# Ref: https://github.com/rust-lang/pkg-config-rs/blob/master/CHANGELOG.md#0320---2021-09-25
pkg-config = "0.3.20"
